
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUNDLE_DIR=$SCRIPT_DIR/../

export JAVAC=
export JAVA_HOME=
export JDK_HOME=
export OS=
export CLASSPATH=
export LD_LIBRARY_PATH=
export LANG=C
export ANT=$BUNDLE_DIR/ant/bin/ant
export PATH=$PATH:$BUNDLE_DIR/ant/bin

export CC=arm-linux-gnueabihf-gcc
export CXX=arm-linux-gnueabihf-g++
export ALT_BOOTDIR=$BUNDLE_DIR/jdk7
export BUILD_ARCH_DIR=arm
export ZERO_BUILD=true
export ZERO_LIBARCH=arm
export ARCH_DATA_MODEL=32
export ZERO_ENDIANNESS=little
export ZERO_ARCHDEF=ARM
export ZERO_ARCHFLAG=-D_LITTLE_ENDIAN
export LIBFFI_LIBS=-lffi
export FT2_LIBS="-L/usr/lib/arm-linux-gnueabihf -lfreetype"
export FT2_CFLAGS=-I/usr/include/freetype2
export ALT_PARALLEL_COMPILE_JOBS=1
export HOTSPOT_BUILD_JOBS=1
export STATIC_CXX=false
export SYSTEM_CUPS=true
export CUPS_LIBS=-lcups
export UNLIMITED_CRYPTO=true
export SYSTEM_ZLIB=true
export ZLIB_LIBS="-L/usr/lib/arm-linux-gnueabihf -lz"
export SYSTEM_LCMS=true
export LCMS_LIBS="-L/usr/lib/arm-linux-gnueabihf -llcms2"
export SYSTEM_JPEG=true
export JPEG_LIBS=-ljpeg
export SYSTEM_PNG=true
export PNG_LIBS="-L/usr/lib/arm-linux-gnueabihf -lpng12"
export PNG_CFLAGS=-I/usr/include/libpng12
export SYSTEM_GIF=true
export GIF_LIBS=-lgif
export SYSTEM_GTK=true
export GTK_LIBS="-L/usr/lib/arm-linux-gnueabihf -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lfontconfig -lfreetype -lgthread-2.0 -pthread -lglib-2.0"
export GTK_CFLAGS="-pthread -I/usr/include/gtk-2.0 -I/usr/lib/arm-linux-gnueabihf/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include"
export SYSTEM_GIO=true
export GIO_LIBS="-L/usr/lib/arm-linux-gnueabihf -lgio-2.0 -lgobject-2.0 -lglib-2.0"
export GIO_CFLAGS="-pthread -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include"
export SYSTEM_GSETTINGS=true
export SYSTEM_GCONF=no
export SYSTEM_FONTCONFIG=true
export FONTCONFIG_LIBS="-L/usr/lib/arm-linux-gnueabihf -lfontconfig -lfreetype"
export FONTCONFIG_CFLAGS=-I/usr/include/freetype2
export COMPILE_AGAINST_SYSCALLS=no
export SYSTEM_KRB5=true
export KRB5_LIBS=-lkrb5
export SYSTEM_PCSC=true
export PCSC_LIBS="-L/usr/lib/arm-linux-gnueabihf -lpcsclite"
export PCSC_CFLAGS="-pthread -I/usr/include/PCSC"
export SYSTEM_SCTP=true
export SCTP_LIBS=-lsctp
export COMPRESS_JARS=true
export ARM32JIT=true
export NO_DOCS=true

